queue_rules:
  - name: test
    merge_method: merge
    update_method: rebase
    merge_conditions:
      - check-success = test
      - "#commits-behind = 0"
    queue_conditions:
      - check-success = test
